openapi: 3.1.0
info:
  title: AlsoAsked
  description: |
    The AlsoAsked API allows you to manage your account, perform searches, access search history, and more.
  version: 1.0.0
  license:
    name: Proprietary
    url: https://alsoasked.com/eula
  termsOfService: https://alsoasked.com/eula
  contact:
    name: AlsoAsked Support
    email: service@alsoasked.com
    url: https://help.alsoasked.com

tags:
- name: account
  description: Operations related to managing an account.
- name: search
  description: Operations related to searches.

servers:
- $ref: ./servers/live.yaml
- $ref: ./servers/sandbox.yaml

security:
- ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
      description: |
        API key required to authenticate requests to the AlsoAsked API. An API key can be obtained by registering for an
        account and creating a key under the developer settings. The key must be passed in the header of each request
        with the key name `X-Api-Key`. Without an API key, all requests will be rejected.
