openapi: 3.1.0
info:
  title: AlsoAsked
  description: |-
    <!-- focus: false -->
    ![AlsoAsked Logo](../assets/images/logo-blue.png)

    ## Overview

    The **AlsoAsked API** offers developers access to 'People Also Ask' search results. This API provides insights into
    frequently asked questions related to specific search queries.

    ## Features

    With the **AlsoAsked API**, you can:

    - Conduct synchronous (waiting for completion) or asynchronous (immediate return with ID; updates via webhooks)
      searches.
    - Retrieve search results.
    - View your past search history.
    - Use webhooks to receive updates on search status, from start to completion or any failures.
    - Access account details, including the count of remaining credits.

    ## Requirements

    A **Pro subscription** is necessary to use the live API. For developers in the initial stages, our sandbox API
    provides a testing environment without returning actual 'People Also Ask' results. This allows for development and
    testing before committing to a **Pro subscription**.

    For more on the **Pro subscription**, visit our [pricing page](https://alsoasked.com/pricing).

    ## Support

    If you have questions, issues, or feedback, please contact us at [help@alsoasked.com](mailto:help@alsoasked.com).
  license:
    name: Proprietary
    url: https://alsoasked.com/eula
  termsOfService: https://alsoasked.com/eula
  contact:
    name: AlsoAsked Support
    email: service@alsoasked.com
    url: https://help.alsoasked.com
  version: 1.0.0
tags:
- $ref: ./tags/Account.yaml
- $ref: ./tags/Search.yaml

servers:
- $ref: ./servers/live.yaml
- $ref: ./servers/sandbox.yaml

components:
  $ref: ./components/index.yaml

paths:
  /account:
    get:
      $ref: ./paths/accounts/get-account.yaml
  /search:
    get:
      $ref: ./paths/search/get-search.yaml
    post:
      $ref: ./paths/search/post-search.yaml
  /search/webhook-example:
    post:
      $ref: ./paths/search/post-search-webhook-example.yaml
  /search/{searchId}:
    get:
      $ref: ./paths/search/get-search-searchId.yaml
    delete:
      $ref: ./paths/search/delete-search-searchId.yaml
